// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxhmqdjwCKCXP5QdqZB5kj10T0ZFJ0CmE',
    appId: '1:565755236724:web:ec8f74476db4a19dbd1c21',
    messagingSenderId: '565755236724',
    projectId: 'soul-finder-2a34c',
    authDomain: 'soul-finder-2a34c.firebaseapp.com',
    storageBucket: 'soul-finder-2a34c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAFs75o5yLRCxGzLXTWFzZywYHEnyr7wY',
    appId: '1:565755236724:android:c220309d1b603d3fbd1c21',
    messagingSenderId: '565755236724',
    projectId: 'soul-finder-2a34c',
    storageBucket: 'soul-finder-2a34c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQBBnB5i1MfKiEqu9l0LJDzQRc6aQ9eTc',
    appId: '1:565755236724:ios:b18bac3ff0910a6abd1c21',
    messagingSenderId: '565755236724',
    projectId: 'soul-finder-2a34c',
    storageBucket: 'soul-finder-2a34c.firebasestorage.app',
    iosBundleId: 'tarc.edu.my.soulFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQBBnB5i1MfKiEqu9l0LJDzQRc6aQ9eTc',
    appId: '1:565755236724:ios:b18bac3ff0910a6abd1c21',
    messagingSenderId: '565755236724',
    projectId: 'soul-finder-2a34c',
    storageBucket: 'soul-finder-2a34c.firebasestorage.app',
    iosBundleId: 'tarc.edu.my.soulFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxhmqdjwCKCXP5QdqZB5kj10T0ZFJ0CmE',
    appId: '1:565755236724:web:12e5ef4358053098bd1c21',
    messagingSenderId: '565755236724',
    projectId: 'soul-finder-2a34c',
    authDomain: 'soul-finder-2a34c.firebaseapp.com',
    storageBucket: 'soul-finder-2a34c.firebasestorage.app',
  );
}
